---
# Valence Infrastructure Inventory
# Two-node deployment for testing and federation

all:
  hosts:
    valence-node-1:
      ansible_host: 64.23.162.8
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      domain: valence.zonk1024.net

    valence-node-2:
      ansible_host: 143.198.139.161
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      domain: valence2.zonk1024.net

  vars:
    # PostgreSQL
    postgres_version: "16"
    postgres_db: valence
    postgres_user: valence
    postgres_password: "{{ lookup('env', 'VALENCE_DB_PASSWORD') }}"

    # Let's Encrypt
    letsencrypt_email: "{{ lookup('env', 'LETSENCRYPT_EMAIL') }}"

    # DigitalOcean Spaces (for backups)
    do_spaces_key: "{{ lookup('env', 'DO_SPACES_KEY') | default('', true) }}"
    do_spaces_secret: "{{ lookup('env', 'DO_SPACES_SECRET') | default('', true) }}"
    do_spaces_bucket: "{{ lookup('env', 'DO_SPACES_BUCKET') | default('', true) }}"
    do_spaces_region: "{{ lookup('env', 'DO_SPACES_REGION') | default('nyc3', true) }}"
